/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.View;

import com.mycompany.webtutor.ListaAlunos;
import com.mycompany.webtutor.ListaProfessores;
import com.mycompany.webtutor.ListaUsuarios;
import com.mycompany.webtutor.Usuario;
import com.mycompany.webtutor.UsuarioAluno;
import com.mycompany.webtutor.UsuarioProfessor;
import com.mycompany.webtutor.Aula;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class TelaAddAula extends javax.swing.JFrame {
    private int id;
    private int idProf;
    
    /**
     * Creates new form TelaAddAula
     */
    public TelaAddAula() {
        initComponents();
        adicionaTabela();
    }
    
     public TelaAddAula(int id) {
        this.id = id;
         initComponents();
         adicionaTabela();
    }    
     
        public void adicionaTabela(){
        // Cria uma cópia da lista de professores para a tabela.
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        List<UsuarioProfessor> list = new ListaProfessores().getUsuarios();
        List<Usuario> list1 = new ListaUsuarios().getUsuarios();
        Object addLinha[] = new Object[4];
        for (int i = 0; i < Usuario.getQuantidadeContas(); i++) {
            
           if(list1.get(i).getUsuario().isProfessor() && list1.get(i).getUsuario()!= null){
                addLinha[0] = list1.get(i).getID();
                addLinha[1] = list1.get(i).getNome();
                addLinha[2] = new ListaProfessores().getUsuarios().get(list1.get(i).getID()).getUsuarioProfessor().getMateria();
                addLinha[3] = new ListaProfessores().getUsuarios().get((list1.get(i).getID())).getFeedback().getPontuacao();
                model.addRow(addLinha);
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdProf = new javax.swing.JTextField();
        enviarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Professor", "Matéria", "Avaliaçao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Digite o ID do professor que deseja pedir a aula.");

        txtIdProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProfActionPerformed(evt);
            }
        });

        enviarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enviarPedido.setText("Enviar pedido");
        enviarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enviarPedido)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1)
                        .addComponent(txtIdProf)))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtIdProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enviarPedido)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new TelaAluno(id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtIdProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProfActionPerformed

    }//GEN-LAST:event_txtIdProfActionPerformed

    private void enviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarPedidoActionPerformed
        new ListaAlunos().getUsuarios().get(id).getUsuarioAluno().addProfessores(new ListaProfessores().getUsuarios().get(Integer.parseInt(txtIdProf.getText())).getUsuarioProfessor());
        new ListaProfessores().getUsuarios().get(Integer.parseInt(txtIdProf.getText())).getUsuarioProfessor().addAlunos(new ListaAlunos().getUsuarios().get(id).getUsuarioAluno());
        Date hoje = new Date();
        Aula aula = new Aula(hoje,new ListaAlunos().getUsuarios().get(id).getUsuarioAluno(),new ListaProfessores().getUsuarios().get(Integer.parseInt(txtIdProf.getText())).getUsuarioProfessor());
        new ListaAlunos().getUsuarios().get(id).getUsuarioAluno().addAula(aula);
        new ListaProfessores().getUsuarios().get(Integer.parseInt(txtIdProf.getText())).getUsuarioProfessor().addAula(aula);
        new TelaAluno(id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_enviarPedidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarPedido;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtIdProf;
    // End of variables declaration//GEN-END:variables
}
